name: Use Reusable CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  use-reusable:
    uses: Hitham07/reusable-workflows/.github/workflows/ci.yml@main
    with:
      node-version: '20'